#!/bin/bash

# Donald E. Knuth, The Art of Computer Programming, Vol. 4A, pp. 324--347
PURE="
SEND+A+TAD+MORE=MONEY
COUPLE+COUPLE=QUARTET
SATURN+URANUS+NEPTUNE+PLUTO=PLANETS
EARTH+AIR+FIRE+WATER=NATURE
HIP*HIP=HURRAY
PI*R*R=AREA
NORTH/SOUTH=EAST/WEST
TWENTY=SEVEN+SEVEN+SIX
TWELVE+NINE+TWO=ELEVEN+SEVEN+FIVE
"
NONPURE="
VIOLIN+VIOLIN+VIOLA=TRIO+SONATA
TWO*TWO=SQUARE
"
SPECIAL="
A/BC+D/EF+G/HI=1
"

# ZEITmagazin, 19/2014, S. 44
ZEIT="
JANUAR+FEBRUAR=STAUSEE
MAERZ+APRIL=MELKEN
MAI+JUNI+JULI=ALPIN
"

# choose examples
EXAMPLES=${PURE}${ZEIT}

PASS=0
FAIL=0
for EX in $EXAMPLES; do
	NUM=$(./puzzle $EX | grep solutions | sed -e "s/ solutions found.//g")
	if [ $NUM -eq 1 ]; then
		echo "$EX passed"
		PASS=$((PASS+1))
	else
		echo "$EX not passed: $NUM solutions"
		FAIL=$((FAIL+1))
	fi
done

echo "$PASS passed, $FAIL failed."
exit $FAIL
